---
title: "DESeq2 Analysis with R: outline"
author: "Bioinfo-Core @ MPI-IE"
date: "`r date() `"
output:
  html_document:
    theme: cosmo
    highlight: textmate
    code_folding: hide
    toc: true
    toc_depth: 1
    toc_float: true
    df_print: paged
---

# Goals

After the course you will be able to

* Perform a full bioinformatics workflow (DESeq2): data input $\to$ output  
* Understand the theory behind RNA-seq data generation and analysis
* Perform exploratory analysis: quality controls, filters  
* Visualize data and results with modern tools  
* Apply complex (multifactorial) experimental designs  
* Obtain and visualise differential genes from simple or complex comparison setups  
* Share workflows with your colleagues.

***

# Prerequistites

* R introduction: data formats, functions, help, plotting, work with packages
* Account for  [workbench](https://workbench.ie-freiburg.mpg.de) or your own local R/Rstudio installation.
* Patience

Note that this course will be based on R version 4.1.3, Bioconductor version 3.14.

***

# Credits

There is lots of useful material out there. This course is heavily influenced by those tutorials

 * https://hbctraining.github.io/DGE_workshop_salmon_online/
 * http://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html
 
We will also be using publicly available data, which has been altered for educational purposes (and should thus be treated as such).

***

# Overview

## 1. Day I: Getting and understanding the data

* Warmup & R-epetition
* Data, Metadata & Design
* Data Exploration
* Quality Control


## 2. Day II: Data Transformations and Model

* Quality Controls & Filtering
* Data Transformations and Normalization
* Size Factors
* Modeling Count Data: NB and Over-dispersion
* Running DESeq2

## 3. Day III: Differentially Expressed Genes

* Multifactorial Designs & Complex Contrasts
* Hypothesis tests: Wald test & LRT
* Inspection & Visualization
* Gene Annotations
* Exporting results

## 4. Day IV: On your own 
* Run a multifactorial DESeq2 Analysis. We'll be around to help.

# Recap - R and libraries.
explain GUI - difference console - env - script - rmds.
***