---
title: "Summary"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: paged
---

```{r installation, eval=FALSE}
BiocManager::install("DESeq2")
```

```{r load}
#.libPaths("/new/location/")     # set if libs are not in default location
library(DESeq2)
library(pheatmap)
library(tidyverse)
```
# Story

- https://pubmed.ncbi.nlm.nih.gov/28790111/
- https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE95077


# Import Data and Metadata
```{r import}
fm="../data/sampleTable2.csv"  # file with metadata
sampleTable <- read.csv(fm, header=FALSE)
colnames(sampleTable)=c("name","filename", "condition","celltype")   # specifications for DESeqDataSetFromHTSeqCount
rownames(sampleTable)=sampleTable$name                    # named rows required for pheatmap
sampleTable$condition=as.factor(sampleTable$condition)    # chr --> factor
sampleTable$celltype=as.factor(sampleTable$celltype)      # chr --> factor

#txi <- tximport(files, type="salmon", tx2gene=t2g, countsFromAbundance = "lengthScaledTPM")
```

# Define Design
```{r design}
my_design <- ~ condition 
# design <- ~ condition + celltype
```


# Create DESeq2 object
dds = data + metadata

```{r combine}
dds <- DESeqDataSetFromHTSeqCount(sampleTable, directory = ".", design = my_design)

# Alternatives:
#dds <- DESeqDataSetFromTximport(txi, colData = sample.table, design = my_desig)
#dds <- DESeqDataSetFromMatrix(matrix, colData=sample.table, design= my_design)

# Precompiled Data sets: just specify design
#library("airway")
#data("airway")
#DESeqDataSet(airway, design = ~ cell + dex)
```

# Data Exploration (PCA, Correlation)
```{r explore1}
dds
pheatmap(counts(dds) %>% head(15))

M <- assay(dds) # get gene-sample matrix
C <- cor(M)     # get sample-sample correlations
pheatmap(C, annotation = sampleTable[,3:4])

#pheatmap(C, annotation = sampleTable[,"condition", drop=FALSE])
```

## with simple transformation

```{r explore2}
rld <- rlog(dds, blind=TRUE)   # simple transform, blind=do not re-estmate dispersion

pheatmap(assay(rld) %>% head(15))

M <- assay(rld)                # get gene-sample matrix
C <- cor(M)                    # get sample-sample correlations
pheatmap(C, annotation = sampleTable[,"condition", drop=FALSE])

plotPCA(rld, intgroup="condition")
```
# Sample and Gene Filtering
Helps 
```{r filtering}
keep = rowSums(counts(dds)) > 1
cat("genes before filter: ", nrow(dds),"\n")
dds = dds[keep,]
cat("genes after filter: ", nrow(dds),"\n")
```

# DESeq2

```{r DEseq2}
dds <- DESeq(dds)  # size factors, dispersion, fit model, run WaldTest
#normalized_counts <- counts(dds, normalized=TRUE) # optional
```

# Quality control
```{r dispersion}
sD <- colSums(counts(dds))  # sequence depth
sF <- sizeFactors(dds)      # sizeFactors

colData(dds)  # sizeFactors have been added to metadata

pheatmap(counts(dds, normalized=FALSE) %>% head(15), cluster_rows=FALSE, main="Raw Counts")
pheatmap(counts(dds, normalized=TRUE) %>% head(15), cluster_rows=FALSE, main="After Norm")

boxplot(log(counts(dds, normalized=FALSE)), las=2, cex.axis=0.75)
boxplot(log(counts(dds, normalized=TRUE)),  las=2, cex.axis=0.75)
boxplot(log(assay(dds)),  las=2, cex.axis=0.75)
boxplot(assay(vst(dds)),  las=2, cex.axis=0.75)

barplot(sF, las=2, cex.names=0.75)
plot(sD, sF)
plotDispEsts(dds, main="Dispersion plot")
```


# Testing
```{r testing}
contrast <- c("condition", "AMIL", "CTRL")
res <- results(dds, contrast = contrast,  alpha = 0.05)

# prefered type="apeglm" --> requires Bioconductor package
res <- lfcShrink(dds, contrast = contrast, type = "normal")  

summary(res, alpha=0.05)
sorted_res <- res %>% data.frame() %>% arrange(padj) 
sorted_res %>% head()

#mcols(res)$description # description of header names
```

# Filter
```{r filter}
padj.cutoff <- 0.05
	
res_tbl <- res %>% 
  data.frame() %>% 
  rownames_to_column(var="gene") %>% 
  as_tibble()
sig_res <- filter(res_tbl, padj < padj.cutoff)
```

# Visualization
```{r visualization}
plotMA(res, ylim=c(-3,3))

sg <- which.min(res$padj) # select gene
plotCounts(dds, gene=sg, intgroup="condition", col = sampleTable$condition)

# Volcano: more customization with EnhancedVolcano()
sorted_res %>% mutate(significant=padj<padj.cutoff) %>% mutate(rank=row_number()) %>% add_rownames("gene_name") %>% 
  ggplot(aes(x=log2FoldChange, y=-log10(padj), color=significant)) + 
  geom_point() + 
  geom_text(aes(label=ifelse(rank<5,gene_name,'')), size = 3, hjust=0,vjust=-0.15)
#  geom_vline(xintercept=0) +
#  geom_vline(xintercept=log2(1),  linetype="dashed", color = "black") + 
#  geom_vline(xintercept=-log2(1), linetype="dashed", color = "black")

  
# heatmap
# gene list
```
# Output
```{r}
fn <- paste( c(contrast, "results.csv"), collapse='_') # generate meaningful filename
write.csv(sorted_res,  file=fn, quote=FALSE)
```

# SessionInfo (for reproducibility)
```{r sessionInfo}
sessionInfo()
```


