# Libraries

During the course we'll use a (limited) number of libraries. These are listed below and are considered installed in the rest of the course.
We make use of the custom 'my_load_namespaces' function (thanks Adrian!) to make sure our libraries are installed and available.


```{r}
my_load_namespaces <- function(packagesToLoad=c(), coreLibraries=c()) {
  # coreLibraries = not explicitly loaded, but required anyway (e.g. dependencies)
  installed_pkgs <- installed.packages()
  
  if (! "BiocManager" %in% installed_pkgs) install.packages("BiocManager")
  
  lapply(c(coreLibraries, packagesToLoad),
         function(x) if (! x %in% installed_pkgs) BiocManager::install(x, ask = FALSE))
  
  lapply(packagesToLoad, function(pkg) {
    suppressPackageStartupMessages(require(pkg, character.only = TRUE))
  })
  
  TRUE
}
```


```{r Libraries, echo=FALSE,warning=FALSE,message=FALSE }
BiocPackages <- c("DESeq2", "tidyverse", "pheatmap")
my_load_namespaces(
  BiocPackages,
  c()
)
BiocManager::valid()
```

***
