channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.1.3
  - r-essentials
  - bioconductor-deseq2
  - bioconductor-ensdb.hsapiens.v75
  - r-tidyverse
  - r-pheatmap
  - r-ashr
  - r-ggrepel
  - r-upsetr