name: render

on:
  pull_request:

defaults:
  run:
      shell: bash -l {0}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: mamba-org/setup-micromamba@main
        with:
          environment-file: configs/conda.yml
          cache-downloads: true
          environment-name: Rdeseq2
      - name: activate_env
        run: |
          micromamba activate Rdeseq2
      - name: render site
        run: |
          Rscript -e "rmarkdown::render_site('rmd/')"